name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

resources:
- repo: self
  clean: all
  fetchDepth: 1

trigger:
  branches:
   include:
    - main/*
  paths:
   include:
    - /*

#variables:
#  - group: devops-dev


pool:
  name: devopslab

stages:
- stage: namespacedev
  displayName: 'Namespace DEV'
  variables:
    - group: devops-dev
  jobs:
  - job: BuildDeploy
    variables:
      - group: devops-dev
    pool:
      name: devopslab

    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace variables ns'
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: |
         devops/k8s/namespace.yaml
        tokenPattern: custom

    - task: Kubernetes@1
      displayName: 'k8s deploy namespace'
      inputs:
        kubernetesServiceEndpoint: k8s
        command: apply
        useConfigurationFile: true
        configuration: devops/k8s/namespace.yaml


- stage: backendbuilddev
  dependsOn:
  - namespacedev
  displayName: 'Backend DEV'
  variables:
    - group: devops-dev
  jobs:
  - job: BuildDeploy
    variables:
      - group: devops-dev
    pool:
      name: devopslab

    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace variables back'
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: |
         backend/app.js
         devops/k8s/backend.yaml
         devops/k8s/back.yaml
        tokenPattern: custom


    - task: Docker@2
      displayName: build backend image
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/dev/backend'
        command: build
        Dockerfile: backend/Dockerfile
        tags: '$(Build.BuildNumber)'
 
#    - task: Anchore@0
#      displayName: container security backend
#      inputs:
#        image: 'gcr.io/the-tree-beneath-329315/devops/dev/backend:$(Build.BuildNumber)'
#        dockerfile: 'backend/Dockerfile'
#        failBuild: false
    #    customPolicyPath: '.anchore/policy.json'
    
    - task: Docker@2
      displayName: push backend image
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/dev/backend'
        tags: '$(Build.BuildNumber)'
        command: push

    - task: Kubernetes@1
      displayName: 'k8s deploy backend'
      inputs:
        kubernetesServiceEndpoint: k8s
        command: apply
        useConfigurationFile: true
        configuration: devops/k8s/back.yaml

- stage: frontendbuilddev
  displayName: 'Frontend DEV'
  dependsOn:
  - namespacedev
  variables:
    - group: devops-dev
  jobs:
  - job: BuildDeploy
    variables:
      - group: devops-dev
    pool:
      name: devopslab
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace variables front'
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: |
         frontend/src/app/user.service.ts
         devops/k8s/frontend.yaml
        tokenPattern: custom


    - task: Docker@2
      displayName: build frontend
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/dev/frontend'
        command: build
        Dockerfile: frontend/Dockerfile
        tags: '$(Build.BuildNumber)'

#    - task: Anchore@0
#      displayName: container security frontend
#      inputs:
#        image: 'gcr.io/the-tree-beneath-329315/devops/dev/frontend:$(Build.BuildNumber)'
#        dockerfile: 'frontend/Dockerfile'
#        failBuild: false
    #    customPolicyPath: '.anchore/policy.json'
    
    - task: Docker@2
      displayName: push frontend
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/dev/frontend'
        tags: '$(Build.BuildNumber)'
        command: push

    - task: Kubernetes@1
      displayName: 'k8s deploy frontend'
      inputs:
        kubernetesServiceEndpoint: k8s
        command: apply
        useConfigurationFile: true
        configuration: devops/k8s/frontend.yaml




- stage: securitytestfrontenddev
  dependsOn:
  - frontendbuilddev
  displayName: 'SecurityTest Frontend DEV'
  variables:
    - group: devops-dev
  jobs:
  - job: securitytest
    pool:
      name: devopslab
    steps:
    - task: owaspzap@1
      inputs:
        scantype: 'targetedScan'
        url: '$(targetscan)'
        port: '80'
        threshold: '120'


- stage: namespacepdn
  dependsOn:
  - securitytestfrontenddev
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  displayName: 'Namespace PDN'
  variables:
    - group: devops-pdn
  jobs:
  - job: BuildDeploy
    variables:
      - group: devops-pdn
    pool:
      name: devopslab

    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace variables ns'
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: |
         devops/k8s/namespace.yaml
        tokenPattern: custom

    - task: Kubernetes@1
      displayName: 'k8s deploy namespace'
      inputs:
        kubernetesServiceEndpoint: k8s
        command: apply
        useConfigurationFile: true
        configuration: devops/k8s/namespace.yaml



- stage: backendbuildpdn
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  displayName: 'Backend PDN'
  dependsOn:
  - backendbuilddev
  - namespacepdn
  variables:
    - group: devops-pdn
  jobs:
  - job: BuildDeploy
    variables:
      - group: devops-pdn
    pool:
      name: devopslab

    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace variables back'
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: |
         backend/app.js
         devops/k8s/back.yaml
         devops/k8s/backend.yaml
        tokenPattern: custom


    - task: Docker@2
      displayName: build backend image
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/pdn/backend'
        command: build
        Dockerfile: backend/Dockerfile
        tags: '$(Build.BuildNumber)'

    
    - task: Docker@2
      displayName: push backend image
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/pdn/backend'
        tags: '$(Build.BuildNumber)'
        command: push


    - task: Kubernetes@1
      displayName: 'k8s deploy backend'
      inputs:
        kubernetesServiceEndpoint: k8s
        command: apply
        useConfigurationFile: true
        configuration: devops/k8s/back.yaml

- stage: rollbackbackendpdn
  displayName: 'Rollback Backend'
  dependsOn:
  - backendbuildpdn
  condition:
  - failed()
  - and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: rollbackbackendpdn
    pool:
      name: devopslab
    steps:
    - task: kubectlgeneral@3
      inputs:
        k8sService: 'k8s'
        subCommand: 'rollout'
        arguments: 'undo deployment backend -n devops-pdn'


- stage: frontendbuildpdn
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  displayName: 'Frontend PDN'
  dependsOn:
  - frontendbuilddev
  - namespacepdn
  variables:
    - group: devops-pdn
  jobs:
  - job: BuildDeploy
    variables:
      - group: devops-pdn
    pool:
      name: devopslab
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace variables front'
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: |
         frontend/src/app/user.service.ts
         devops/k8s/frontend.yaml
        tokenPattern: custom


    - task: Docker@2
      displayName: build frontend
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/pdn/frontend'
        command: build
        Dockerfile: frontend/Dockerfile
        tags: '$(Build.BuildNumber)'
    
    - task: Docker@2
      displayName: push frontend
      inputs:
        containerRegistry: 'gcp-registry'
        repository: 'the-tree-beneath-329315/devops/pdn/frontend'
        tags: '$(Build.BuildNumber)'
        command: push

    - task: Kubernetes@1
      displayName: 'k8s deploy frontend'
      inputs:
        kubernetesServiceEndpoint: k8s
        command: apply
        useConfigurationFile: true
        configuration: devops/k8s/frontend.yaml


- stage: rollbackfrontendpdn
  displayName: 'Rollback Frontend'
  dependsOn:
  - frontendbuildpdn
  condition: 
  - failed()
  - and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: rollbackfrontendpdn
    pool:
      name: devopslab
    steps:
    - task: kubectlgeneral@3
      inputs:
        k8sService: 'k8s'
        subCommand: 'rollout'
        arguments: 'undo deployment frontend -n devops-pdn'