name: $(Date:yyyyMMdd)$(Rev:.r)
variables: 
- group: 'var-front' # variable group
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: Default
    steps:
    # - task: Docker@1
    #   displayName: build
    #   inputs:
    #     command: build
    #     dockerFile: frontend/Dockerfile
    #     imageName: 'registry.digitalocean.com/reto-devops/front:$(Build.BuildId)'
    - script: echo Builded!
    # - task: Docker@1
    #   displayName: push
    #   inputs:
    #     containerregistrytype: 'Container Registry'
    #     dockerRegistryEndpoint: 'DigitalOcean-DockerRegistry'
    #     command: push
    #     imageName: 'registry.digitalocean.com/reto-devops/front:$(Build.BuildId)'
- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: frontend
        targetFiles: '**/*.yaml'
    - task: Kubernetes@1
      displayName: 'kubectl apply'
      inputs:
        kubernetesServiceEndpoint: 'DigitalOcean-k8s'
        command: apply
        arguments: '-f $(System.DefaultWorkingDirectory)/frontend/deployment-front.yaml'

