name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: value1
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: Default
    steps:
    - task: Docker@1
      displayName: build
      inputs:
        command: build
        dockerFile: frontend/Dockerfile
        imageName: 'registry.digitalocean.com/reto-devops/front:$(Build.BuildId)'
    - script: echo Builded!
    - task: Docker@1
      displayName: push
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DigitalOcean-DockerRegistry'
        command: push
        imageName: 'registry.digitalocean.com/reto-devops/front:$(Build.BuildId)'
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - task: Kubernetes@1
      displayName: 'kubectl apply'
      inputs:
        kubernetesServiceEndpoint: 'DigitalOcean-k8s'
        command: apply
        arguments: '-f $(System.DefaultWorkingDirectory)/frontend/deployment-front.yaml'
        - script: echo Deploy!

