name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - backend/*
variables: 
- group: 'var-back'
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: Default
    steps:
    - task: Docker@1
      displayName: build
      inputs:
        command: build
        dockerFile: backend/Dockerfile
        imageName: 'registry.digitalocean.com/reto-devops/back:$(Build.BuildId)'
    - script: echo Builded!
    - task: Docker@1
      displayName: push
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DigitalOcean-DockerRegistry'
        command: push
        imageName: 'registry.digitalocean.com/reto-devops/back:$(Build.BuildId)'
- stage: Deploy_DEV
  jobs:
  - job: DeployJob
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: backend
        targetFiles: |
          *.yaml
          app.js
    - task: Kubernetes@1
      displayName: 'kubectl apply'
      inputs:
        kubernetesServiceEndpoint: 'DigitalOcean-k8s'
        command: apply
        arguments: '-f $(System.DefaultWorkingDirectory)/backend/deployment-back.yaml -n dev'
- stage: Deploy_PDN
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/trunk'))
  jobs:
  - job: DeployJob
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: backend
        targetFiles: |
          *.yaml
          app.js
    - task: Kubernetes@1
      displayName: 'kubectl apply'
      inputs:
        kubernetesServiceEndpoint: 'DigitalOcean-k8s'
        command: apply
        arguments: '-f $(System.DefaultWorkingDirectory)/backend/deployment-back.yaml -n pdn'
