apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-back
spec:
  selector:
    matchLabels:
      app: back
  replicas: #{replicas}#
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: #{image-name}#
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-back
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
