name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
- job: create Dev ns
  steps:
- task: Kubernetes@1
  displayName: 'kubectl create'
  inputs:
    kubernetesServiceEndpoint: 'DigitalOcean-k8s'
    command: create
    arguments: '-f $(System.DefaultWorkingDirectory)/infra/namespace-dev.yaml'