---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "backend"
  namespace: "#{namespace}#"
  labels:
    app: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "backend"
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      containers:
      - name: "backend-1"
        image: "#{containerimage-backend}#"
        ports:
        - containerPort: 3000